### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by GTARaven** [sblask/webextension-open-tabs-next-to-current#45] opened 2017-12-06 16:33 UTC
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [X] Firefox Quantum 57.0.1 (64 Bit)
- [ ] Chrome

### What is your operating system?

- [X] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)
When i restart the Browser next day with last session, the last tab is moved to the first place, right behind the sticky tabs and before the other tabs.

**Comment by sblask** [comment] 2017-12-06 19:51
Duplicate of #30

**Closed by sblask** 2017-12-06 19:51 UTC
